
export const ADD_CART_REQUEST = 'ADD_CART_REQUEST';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const ADD_CART_FAILED = 'ADD_CART_FAILED';

export const GET_CART_PRODUCT_REQUEST = 'GET_CART_PRODUCT_REQUEST';
export const GET_CART_PRODUCT_SUCCESS = 'GET_CART_PRODUCT_SUCCESS';
export const GET_CART_PRODUCT_FAILED = 'GET_CART_PRODUCT_FAILED';
  